name: "CI"

on:
  pull_request:
  push:

jobs:
  installer_test:
    runs-on: ubuntu-20.04
    steps:
    - uses: cachix/install-nix-action@v22
      with:
          nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-shell -p hello --command hello
